<?php
/**
 * Created by PhpStorm.
 * User: mariusngaboyamahina
 * Date: 3/22/17
 * Time: 10:20 PM
 */

namespace common\components;


use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use common\helpers\Helpers;
use common\helpers\RecordHelpers;
use common\helpers\DataHelpers;

class SuperController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public static function accessDataByIds($param)
    {
        return [
            'get_cells' => DataHelpers::getCells($param),
            'get_sectors' => DataHelpers::getSectors($param),
            'get_services' => DataHelpers::getServices($param),
            'get_districts' => DataHelpers::getDistricts($param),
            'get_place_by_id' => DataHelpers::getPlaceById($param),
            'get_data_in_array' => Helpers::getDataInArray($param),
            'get_place_contacts' => DataHelpers::getPlaceContacts($param),
            'get_post_categories' => DataHelpers::getPostCategories($param),
            'get_places_with_status' => DataHelpers::getPlacesWithStatuses($param),
            'get_post_category_id' => DataHelpers::getPostsByPostCategoryId($param),
            'get_services_by_category_id' => DataHelpers::getServicesByCategoryId($param),
            'get_posts_by_post_category_id' => DataHelpers::getPostsByPostCategoryId($param),

        ];
    }

    public static function accessData()
    {
        return [
            'place_model' => DataHelpers::getPlace(),
            'get_keywords' => DataHelpers::getKeywords(),
            'has_profile' => RecordHelpers::hasProfile(),
            'get_all_places' => DataHelpers::getAllPlaces(),
            'all_services' => DataHelpers::getAllServices(),
            'all_categories' => DataHelpers::getAllCategories(),
            'profile_picture' => RecordHelpers::profilePicture(),
            'get_upcoming_events' => DataHelpers::getUpcomingEvents(),
            'get_profile_picture' => RecordHelpers::getProfilePicture(),
            'all_post_categories' => DataHelpers::getAllPostCategories(),
        ];
    }

    public function accessDistricts($model){
        $district_data = $this->accessDataByIds($model->district_id);
        $districts = $district_data['get_districts'];
        $district_data_in_array = $this->accessDataByIds($districts);
        $district_data_in_array['get_data_in_array'];
        return $district_data_in_array['get_data_in_array'];
    }

    public function accessSectors($model){
        $sector_data = $this->accessDataByIds($model->district_id);
        $sectors = $sector_data['get_sectors'];
        $sector_data_in_array = $this->accessDataByIds($sectors);
        return $sector_data_in_array['get_data_in_array'];
    }

    public function accessCells($model){
        $cell_data = $this->accessDataByIds($model->sector_id);
        $cells = $cell_data['get_cells'];
        $cell_data_in_array = $this->accessDataByIds($cells);
        return $cell_data_in_array['get_data_in_array'];
    }

    public function accessServices($model){
        $service_data = $this->accessDataByIds($model->service_id);
        $services = $service_data['get_services'];
        $service_data_in_array = $this->accessDataByIds($services);
        return $service_data_in_array['get_data_in_array'];
    }

    public function accessPostCategories($model){
        $data = $this->accessDataByIds($model->post_type_id);
        $post_categories = $data['get_post_categories'];
        $post_categories_data_in_array = $this->accessDataByIds($post_categories);
        return $post_categories_data_in_array['get_data_in_array'];
    }

}